module.exports = {
	/* 继承其它规则 */
	extends: [
		'stylelint-config-standard', // 配置stylelint拓展插件
		'stylelint-config-recommended-vue', // 配置 vue 样式格式化
		'stylelint-config-recommended-vue/scss', // 支持 sass, 配置 vue 样式格式化
		'stylelint-config-recess-order', // 配置stylelint css属性书写顺序插件,
	],
	overrides: [
		// 扫描 .vue/html 文件中的<style>标签内的样式
		{
			files: ['**/*.{vue,html}'],
			customSyntax: 'postcss-html',
		},
	],
	rules: {
		'order/properties-order': [
			'position',
			'display',
			'float',
			'top',
			'right',
			'bottom',
			'left',
			'z-index',
			'overflow',
			'clear',
			'width',
			'height',
			'max-width',
			'max-height',
			'min-width',
			'min-height',
			'padding',
			'padding-top',
			'padding-right',
			'padding-bottom',
			'padding-left',
			'margin',
			'margin-top',
			'margin-right',
			'margin-bottom',
			'margin-left',
			'margin-collapse',
			'margin-top-collapse',
			'margin-right-collapse',
			'margin-bottom-collapse',
			'margin-left-collapse',
			'font',
			'font-family',
			'font-size',
			'font-smoothing',
			'osx-font-smoothing',
			'font-style',
			'font-weight',
			'hyphens',
			'src',
			'line-height',
			'letter-spacing',
			'word-spacing',
			'color',
			'text-align',
			'text-decoration',
			'text-indent',
			'text-overflow',
			'text-rendering',
			'text-size-adjust',
			'text-shadow',
			'text-transform',
			'word-break',
			'word-wrap',
			'white-space',
			'vertical-align',
			'list-style',
			'content',
			'box-shadow',
			'border-radius',
			'transform',
		],
	},
};
